#!/bin/bash
# Run agent swarm workflow demo
# Demonstrates: branch creation -> edit -> validate -> commit -> push -> PR

set -euo pipefail

REPO_DIR="/opt/samdev-wiki"
TIMESTAMP=$(date +%Y%m%d%H%M%S)
TASK_NAME="workflow-demo-$TIMESTAMP"
BRANCH_NAME="agent/$TASK_NAME"

echo "=== Agent Swarm Workflow Demo ==="
echo ""

cd "$REPO_DIR"

# Ensure we're on main and up to date
echo "1. Ensuring clean state..."
git checkout main
git pull origin main 2>/dev/null || true

# Create new branch
echo "2. Creating branch: $BRANCH_NAME"
git checkout -b "$BRANCH_NAME"

# Make a test change
echo "3. Making test changes..."
cat > docs/agent-swarm-demo.txt << EOF
# Agent Swarm Demo File

This file demonstrates the agent swarm workflow.

## Branch Information
- Name: $BRANCH_NAME
- Created: $(date -u)
- Task: $TASK_NAME

## Purpose
This is an automatically generated file to demonstrate:
1. Branch creation with prefix 'agent/'
2. File editing
3. Commit with conventional commits
4. Push to remote
5. Pull request creation

---
*Generated by agent swarm demo script*
EOF

git add docs/agent-swarm-demo.txt

# Validate
echo "4. Validating changes..."
git status --short

# Commit
echo "5. Committing changes..."
git commit -m "docs: add agent swarm demonstration file

This commit demonstrates the complete agent swarm workflow:
- Branch created with agent/ prefix
- Changes validated
- Conventional commit format used

Task: $TASK_NAME
"

# Push using gh CLI authentication
echo "6. Pushing branch..."
if git push -u origin "$BRANCH_NAME" 2>&1; then
    echo ""
    echo "✓ Branch pushed successfully!"
else
    echo ""
    echo "Note: Push failed - check gh authentication"
    echo "Run: gh auth status"
fi

echo ""
echo "Branch URL: https://github.com/Ramasanjaya22/samdev-wiki/tree/$BRANCH_NAME"
echo ""
echo "To create PR: gh pr create --title 'docs: add agent swarm demo' --head $BRANCH_NAME --base main"